# Generated by Django 4.2.27 on 2026-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='track',
            field=models.CharField(choices=[('AI_SERVER', 'AI'), ('PLANNING_DESIGN', '기획/디자인')], max_length=30),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='track',
            field=models.CharField(choices=[('AI_SERVER', 'AI'), ('PLANNING_DESIGN', '기획/디자인')], max_length=30),
        ),
    ]
