# Generated by Django 4.2.27 on 2026-03-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_resultnotificationsettings_doc_result_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultnotificationsettings',
            name='track_ai_server_open',
            field=models.BooleanField(default=True, verbose_name='AI 트랙 지원 활성화'),
        ),
        migrations.AddField(
            model_name='resultnotificationsettings',
            name='track_backend_open',
            field=models.BooleanField(default=True, verbose_name='백엔드 트랙 지원 활성화'),
        ),
        migrations.AddField(
            model_name='resultnotificationsettings',
            name='track_frontend_open',
            field=models.BooleanField(default=True, verbose_name='프론트엔드 트랙 지원 활성화'),
        ),
        migrations.AddField(
            model_name='resultnotificationsettings',
            name='track_planning_design_open',
            field=models.BooleanField(default=True, verbose_name='기획/디자인 트랙 지원 활성화'),
        ),
    ]
