# Generated by Django 4.2.27 on 2026-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.CharField(choices=[('TOP', '1~6월'), ('BOTTOM', '7~12월')], max_length=6)),
                ('row', models.IntegerField(default=0, help_text='0=메인행, 1+=상세행')),
                ('col_start', models.IntegerField(help_text='시작 열 (1-6)')),
                ('col_span', models.IntegerField(default=1, help_text='열 너비 (1-6)')),
                ('label', models.CharField(max_length=100)),
                ('bg_color', models.CharField(default='#F8F8FC', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='같은 half+row 내 정렬 순서')),
            ],
            options={
                'ordering': ['half', 'row', 'order'],
            },
        ),
    ]
