# Generated by Django 4.2.27 on 2026-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_education_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education_track',
            field=models.CharField(blank=True, choices=[('PLANNING_DESIGN', '기획/디자인'), ('FRONTEND', '프론트엔드'), ('BACKEND', '백엔드'), ('AI_SERVER', 'AI')], default=None, max_length=30, null=True),
        ),
    ]
